sudo: required

language: php

php:
  - '7.0'
  - nightly

services:
  - docker

before_script: composer install

script:
  - docker build -t tec/intern/rest-api-web .
  - docker tag tec/intern/rest-api-web node2.didithilmy.com/tec/intern/rest-api-web
  - docker push node2.didithilmy.com/tec/intern/rest-api-web